#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StarKargo.Resource", IsApplication=true)]

namespace StarKargo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int agent_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int location_array = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int lot_array = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int role_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barcode = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Logo_Login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Logo_Module = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logout = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int unlock = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int ImgBtnChangePwd = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int ImgBtnLogout = 2131099649;
			
			// aapt resource value: 0x7f06001f
			public const int ImgBtnScan = 2131099679;
			
			// aapt resource value: 0x7f060042
			public const int RememberMe = 2131099714;
			
			// aapt resource value: 0x7f060059
			public const int Text = 2131099737;
			
			// aapt resource value: 0x7f060047
			public const int Text1 = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int Text2 = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int Text3 = 2131099721;
			
			// aapt resource value: 0x7f060046
			public const int btnAddUser = 2131099718;
			
			// aapt resource value: 0x7f06001d
			public const int btnCancel = 2131099677;
			
			// aapt resource value: 0x7f060038
			public const int btnCompleNextDeliver = 2131099704;
			
			// aapt resource value: 0x7f060037
			public const int btnComplete = 2131099703;
			
			// aapt resource value: 0x7f06005c
			public const int btnDelete = 2131099740;
			
			// aapt resource value: 0x7f060055
			public const int btnDeliverComplete = 2131099733;
			
			// aapt resource value: 0x7f06000d
			public const int btnDeliverPackage = 2131099661;
			
			// aapt resource value: 0x7f060027
			public const int btnDone = 2131099687;
			
			// aapt resource value: 0x7f060044
			public const int btnForgotPwd = 2131099716;
			
			// aapt resource value: 0x7f06004f
			public const int btnLoadComplete = 2131099727;
			
			// aapt resource value: 0x7f060009
			public const int btnLoadContainer = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int btnLookupPackage = 2131099663;
			
			// aapt resource value: 0x7f060057
			public const int btnNo = 2131099735;
			
			// aapt resource value: 0x7f06003c
			public const int btnOK = 2131099708;
			
			// aapt resource value: 0x7f060013
			public const int btnPending = 2131099667;
			
			// aapt resource value: 0x7f06004c
			public const int btnReceiveComplete = 2131099724;
			
			// aapt resource value: 0x7f060007
			public const int btnReceivePackage = 2131099655;
			
			// aapt resource value: 0x7f060031
			public const int btnSave = 2131099697;
			
			// aapt resource value: 0x7f06003d
			public const int btnSubmit = 2131099709;
			
			// aapt resource value: 0x7f060052
			public const int btnUnLoadComplete = 2131099730;
			
			// aapt resource value: 0x7f06000b
			public const int btnUnloadContainer = 2131099659;
			
			// aapt resource value: 0x7f06001b
			public const int btnUpdatePwd = 2131099675;
			
			// aapt resource value: 0x7f060011
			public const int btnUsers = 2131099665;
			
			// aapt resource value: 0x7f060056
			public const int btnYes = 2131099734;
			
			// aapt resource value: 0x7f06001c
			public const int emptySpace = 2131099676;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060032
			public const int lblBarcode = 2131099698;
			
			// aapt resource value: 0x7f060039
			public const int lblPackageCount = 2131099705;
			
			// aapt resource value: 0x7f06005b
			public const int linearLayout1 = 2131099739;
			
			// aapt resource value: 0x7f06003b
			public const int linearLayoutBtns = 2131099707;
			
			// aapt resource value: 0x7f06003f
			public const int listView1 = 2131099711;
			
			// aapt resource value: 0x7f060045
			public const int listViewUsers = 2131099717;
			
			// aapt resource value: 0x7f060043
			public const int login = 2131099715;
			
			// aapt resource value: 0x7f060041
			public const int password = 2131099713;
			
			// aapt resource value: 0x7f060036
			public const int relativeLayout1 = 2131099702;
			
			// aapt resource value: 0x7f06001a
			public const int relativeLayout2 = 2131099674;
			
			// aapt resource value: 0x7f060030
			public const int relativeLayout3 = 2131099696;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout4 = 2131099648;
			
			// aapt resource value: 0x7f060058
			public const int spinAgentID = 2131099736;
			
			// aapt resource value: 0x7f06002e
			public const int spinLocationID = 2131099694;
			
			// aapt resource value: 0x7f06003e
			public const int spinLotID = 2131099710;
			
			// aapt resource value: 0x7f06002d
			public const int spinRoleID = 2131099693;
			
			// aapt resource value: 0x7f06005a
			public const int spinShippedLotID = 2131099738;
			
			// aapt resource value: 0x7f060005
			public const int tableLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int tableRow1 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int tableRow2 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow3 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow4 = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow5 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int tableRow6 = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int tableRow7 = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060029
			public const int textView2 = 2131099689;
			
			// aapt resource value: 0x7f060014
			public const int textView3 = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int textView4 = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int textView5 = 2131099672;
			
			// aapt resource value: 0x7f06002b
			public const int textView6 = 2131099691;
			
			// aapt resource value: 0x7f060023
			public const int txtAgentID = 2131099683;
			
			// aapt resource value: 0x7f06001e
			public const int txtBarcode = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int txtConfirmPwd = 2131099673;
			
			// aapt resource value: 0x7f060035
			public const int txtDateDelivered = 2131099701;
			
			// aapt resource value: 0x7f060053
			public const int txtDeliver = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int txtDeliverCount = 2131099732;
			
			// aapt resource value: 0x7f060025
			public const int txtDeliveryDate = 2131099685;
			
			// aapt resource value: 0x7f06002c
			public const int txtEmail = 2131099692;
			
			// aapt resource value: 0x7f060015
			public const int txtExistingPwd = 2131099669;
			
			// aapt resource value: 0x7f060028
			public const int txtFirstName = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int txtLastName = 2131099690;
			
			// aapt resource value: 0x7f06004e
			public const int txtLoadCount = 2131099726;
			
			// aapt resource value: 0x7f06004d
			public const int txtLoadPack = 2131099725;
			
			// aapt resource value: 0x7f060024
			public const int txtLotNo = 2131099684;
			
			// aapt resource value: 0x7f060017
			public const int txtNewPwd = 2131099671;
			
			// aapt resource value: 0x7f06003a
			public const int txtPackageCount = 2131099706;
			
			// aapt resource value: 0x7f060034
			public const int txtPackageQty = 2131099700;
			
			// aapt resource value: 0x7f06002f
			public const int txtPassword = 2131099695;
			
			// aapt resource value: 0x7f06004b
			public const int txtRecCount = 2131099723;
			
			// aapt resource value: 0x7f06004a
			public const int txtRecPack = 2131099722;
			
			// aapt resource value: 0x7f060026
			public const int txtReceivedBy = 2131099686;
			
			// aapt resource value: 0x7f060051
			public const int txtUnLoadCount = 2131099729;
			
			// aapt resource value: 0x7f060050
			public const int txtUnLoadPack = 2131099728;
			
			// aapt resource value: 0x7f060020
			public const int txtViewPackageCount = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int txtViewPackageOrder = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int txtViewPackageStatus = 2131099682;
			
			// aapt resource value: 0x7f060033
			public const int txtVwScanPackage = 2131099699;
			
			// aapt resource value: 0x7f060040
			public const int userName = 2131099712;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Admin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChangePassword = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CheckPackage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateUser = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DeliveryPackage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DialogLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ForgotPassword = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fullfillment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int LoadContainer = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Login = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ManageUser = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PendingPackage = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ReceiveOKDialog = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ReceivePackage = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int row_layout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int spinner_item = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int UnloadContainer = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int UpdateUser = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int user_row_layout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Warehouse = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
